foreground         #EBF6F7
background         #141718
cursor             #77A5A2
active_tab_foreground     #141718
active_tab_background     #EBF6F7
inactive_tab_foreground   #EBF6F7
inactive_tab_background   #141718
active_border_color   #EBF6F7
inactive_border_color #141718
bell_border_color     #3C6765
color0      #3D4243
color1		#3C6765
color2		#3C6A67
color3		#3E897F
color4		#3E897F
color5		#0298B2
color6		#94ACAD
color7		#DAEAEB
color8		#98A3A4
color9		#3D7673
color10		#3D7A75
color11		#138F7E
color12		#138F7E
color13		#03CAED
color14		#C5E5E7
color15		#DAEAEB