foreground         #F7D2E0
background         #171314
cursor             #B27288
active_tab_foreground     #171314
active_tab_background     #F7D2E0
inactive_tab_foreground   #F7D2E0
inactive_tab_background   #171314
active_border_color   #F7D2E0
inactive_border_color #171314
bell_border_color     #624652
color0      #433D40
color1		#624652
color2		#8F485F
color3		#9B4F64
color4		#DB5072
color5		#DB5072
color6		#E77DA7
color7		#EBB6CB
color8		#A47F8E
color9		#624652
color10		#8F485F
color11		#9B4F64
color12		#DB5072
color13		#DB5072
color14		#E77DA7
color15		#EBB6CB