# source = ~/.config/hypr/conf/monitors/nwg-displays.conf

monitor=desc:BBC HDP-V104 demoset-1,1920x1080@60.0,5000x5000,1.0 # HDMI-A-1
monitor=desc:BBC HDP-V104 demoset-1,disable
monitor=desc:LG Electronics LG ULTRAGEAR 310NTCZ6H379,3440x1440@160.0,-1440x-1560,1.0,transform,1 # DP-2
monitor=desc:LG Electronics LG ULTRAGEAR+ 411NTTQ06481,3840x2160@240.08,0x0,1.25 # 4K to 1440p - DP-3