[config]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.wofi]
input_path = '~/.config/matugen/templates/wofi-style.css'
output_path = '~/.config/wofi/style.css'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.wlogout]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wlogout/colors.css'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors.css'

[templates.sddm]
input_path = "~/.config/matugen/templates/sddm.conf"
output_path = "~/.config/matugen/sddm.conf"

[templates.ohmyposh]
input_path = '~/.config/matugen/templates/ohmyposh-colors.json'
output_path = '~/.config/ohmyposh/colors.json'
post_hook = "jq --slurpfile palette ~/.config/ohmyposh/colors.json '. + $palette[0]' ~/.config/ohmyposh/EDM115-newline.omp.json > /tmp/new_theme.json && mv /tmp/new_theme.json ~/.config/ohmyposh/EDM115-newline.omp.json"