# Optional QoL
splash = false
ipc = on

# # Preload the image(s) you use
# preload = "$HOME/Pictures/Wallpapers/Cachy depths 5K.png"

# # Assign wallpapers per monitor (use names from `hyprctl monitors`)
# # Example with two outputs DP-1 and DP-2:
# wallpaper = DP-1,"$HOME/Pictures/Wallpapers/Cachy depths 5K.png"
# wallpaper = DP-2,"$HOME/Pictures/Wallpapers/Cachy depths 5K.png"
