# https://wiki.hypr.land/Configuring/
# Don't edit this file directly, use the files in ~/.config/hypr/conf/

###############
### MONITOR ###
###############
source = ~/.config/hypr/conf/monitor.conf

##############
### CURSOR ###
##############
source = ~/.config/hypr/conf/cursor.conf

###################
### ENVIRONMENT ###
###################
source = ~/.config/hypr/conf/environment.conf

################
### KEYBOARD ###
################
source = ~/.config/hypr/conf/keyboard.conf

#############
### THEME ###
#############
source = ~/.config/hypr/themes/orange_gray.conf

#################
### AUTOSTART ###
#################
source = ~/.config/hypr/conf/autostart.conf

#################
### ANIMATION ###
#################
source = ~/.config/hypr/conf/animation.conf

##############
### WINDOW ###
##############
source = ~/.config/hypr/conf/window.conf

###################
### WINDOW RULE ###
###################
source = ~/.config/hypr/conf/windowrule.conf

##################
### DECORATION ###
##################
source = ~/.config/hypr/conf/decoration.conf

##############
### LAYOUT ###
##############
source = ~/.config/hypr/conf/layout.conf

#################
### WORKSPACE ###
#################
source = ~/.config/hypr/conf/workspace.conf

##############
### CUSTOM ###
##############
source = ~/.config/hypr/conf/custom.conf

##################
### KEYBINDING ###
##################
source = ~/.config/hypr/conf/keybinding.conf

############
### MISC ###
############
source = ~/.config/hypr/conf/misc.conf