# Hyprland master configuration file to source all custom configs at once
# Make sure $DOTFILES_PATH matches your actual dotfiles location
# Intended for use with the ML4W dotfiles setup

$DOTFILES_PATH = $HOME/Dev/dotfiles/.config/hypr

source = $DOTFILES_PATH/conf/animation.conf
source = $DOTFILES_PATH/conf/autostart.conf
source = $DOTFILES_PATH/conf/cursor.conf
source = $DOTFILES_PATH/conf/custom.conf
source = $DOTFILES_PATH/conf/decoration.conf
source = $DOTFILES_PATH/conf/environment.conf
source = $DOTFILES_PATH/conf/keybinding.conf
source = $DOTFILES_PATH/conf/keyboard.conf
source = $DOTFILES_PATH/conf/layout.conf
source = $DOTFILES_PATH/conf/misc.conf
source = $DOTFILES_PATH/conf/ml4w.conf
source = $DOTFILES_PATH/conf/monitor.conf
source = $DOTFILES_PATH/conf/window.conf
source = $DOTFILES_PATH/conf/windowrule.conf
source = $DOTFILES_PATH/conf/workspace.conf