- 1.1.14-112-g694caf63
- _NAME: G903 LIGHTSPEED Wireless Gaming Mouse w/ HERO
  _absent: [hi-res-scroll, lowres-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert, thumb-scroll-mode, report_rate_extended, pointer_speed,
    dpi_extended, speed-change, backlight, backlight_level, backlight_duration_hands_out, backlight_duration_hands_in, backlight_duration_powered, backlight-timed,
    led_control, led_zone_, brightness_control, per-key-lighting, fn-swap, reprogrammable-keys, persistent-remappable-keys, divert-keys, disable-keyboard-keys,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, change-host, gesture2-gestures, gesture2-divert, gesture2-params, sidetone,
    equalizer, adc_power_management]
  _battery: 4097
  _modelId: 4087C0910000
  _sensitive: {dpi: ignore, hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore, rgb_control: true, rgb_zone_1: true,
    rgb_zone_2: true}
  _serial: 50E492D5
  _unitId: 50E492D5
  _wpid: '4087'
  dpi: 800
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  onboard_profiles: 1
  report_rate: 1
  rgb_control: 1
  rgb_zone_1: !LEDEffectSetting {ID: 0, color: 16777215, intensity: 0, period: 100, ramp: 0, speed: 0}
  rgb_zone_2: !LEDEffectSetting {ID: 1, color: 16777215, intensity: 0, period: 100, ramp: 0, speed: 0}
- _NAME: G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, report_rate_extended, pointer_speed, dpi, dpi_extended, speed-change, backlight, backlight_level, backlight_duration_hands_out, backlight_duration_hands_in,
    backlight_duration_powered, backlight-timed, led_control, led_zone_, fn-swap, reprogrammable-keys, persistent-remappable-keys, disable-keyboard-keys,
    crown-smooth, divert-crown, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4097
  _modelId: B35F408EC343
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore, rgb_control: true, rgb_zone_1: true, rgb_zone_2: true}
  _serial: 097ACBE3
  _unitId: 097ACBE3
  _wpid: 408E
  brightness_control: 100
  change-host: null
  divert-gkeys: false
  divert-keys: {209: 0, 210: 0}
  m-key-leds: {1: false, 2: false, 4: false}
  mr-key-led: false
  onboard_profiles: 1
  per-key-lighting: {1: -1, 2: -1, 3: -1, 4: -1, 5: -1, 6: -1, 7: -1, 8: -1, 9: -1, 10: -1, 11: -1, 12: -1, 13: -1, 14: -1, 15: -1, 16: -1, 17: -1, 18: -1,
    19: -1, 20: -1, 21: -1, 22: -1, 23: -1, 24: -1, 25: -1, 26: -1, 27: -1, 28: -1, 29: -1, 30: -1, 31: -1, 32: -1, 33: -1, 34: -1, 35: -1, 36: -1, 37: -1,
    38: -1, 39: -1, 40: -1, 41: -1, 42: -1, 43: -1, 44: -1, 45: -1, 46: -1, 47: -1, 48: -1, 49: -1, 50: -1, 51: -1, 52: -1, 53: -1, 54: -1, 55: -1, 56: -1,
    57: -1, 58: -1, 59: -1, 60: -1, 61: -1, 62: -1, 63: -1, 64: -1, 65: -1, 66: -1, 67: -1, 68: -1, 69: -1, 70: -1, 71: -1, 72: -1, 73: -1, 74: -1, 75: -1,
    76: -1, 77: -1, 78: -1, 79: -1, 97: -1, 98: -1, 99: -1, 100: -1, 101: -1, 102: -1, 103: -1, 104: -1, 105: -1, 106: -1, 107: -1, 108: -1, 109: -1, 110: -1,
    111: -1, 153: -1, 155: -1, 156: -1, 157: -1, 158: -1, 210: -1}
  report_rate: 1
  rgb_control: 1
  rgb_zone_1: !LEDEffectSetting {ID: 1, color: 16777215, intensity: 0, period: 100, ramp: 0, speed: 0}
  rgb_zone_2: !LEDEffectSetting {ID: 1, color: 16777215, intensity: 0, period: 100, ramp: 0, speed: 0}