# https://wiki.hypr.land/Configuring/Variables/#general
general {
    gaps_in = 3
    gaps_out = 3
    border_size = 2
    col.active_border = $accent
    col.inactive_border = $inactive
    resize_on_border = false
    layout = dwindle
}