# Use when waybar stops loading quickly
# exec-once = pkill xdg-desktop-portal; pkill xdg-desktop-portal-wlr; \
#             dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP; \
#             /usr/lib/xdg-desktop-portal-wlr & /usr/lib/xdg-desktop-portal &

exec-once = swayosd-server

exec-once = sunshine

exec-once = sh -c 'sleep 0.1; hyprctl dispatch focusmonitor DP-3; hyprctl dispatch movecursor 1280 720'
