# Use when waybar stops loading quickly
# exec-once = pkill xdg-desktop-portal; pkill xdg-desktop-portal-wlr; \
#             dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP; \
#             /usr/lib/xdg-desktop-portal-wlr & /usr/lib/xdg-desktop-portal &

exec-once = swayosd-server

exec-once = sunshine

# Needed because Hyprland makes the mouse focus the lower numbered monitor
exec-once = hyprctl dispatch focusmonitor DP-3