# Steam
windowrule = tile, class:steam
windowrule = monitor:DP-3, class:steam

# Steam Friends List
windowrule = float, class:steam, title: Friends List
windowrule = size 350 600, class:steam, title: Friends List
# windowrule = move 25% 25%, class:steam, title: Friends List
windowrule = center, class:steam, title: Friends List

# Steam Settings
windowrule = float, class:steam, title: Steam Settings
windowrule = center, class:steam, title: Steam Settings

# Steam Games
windowrule = monitor:DP-3, class:steam_app_.*
windowrule = workspace emptynm, class:steam_app_.*
windowrule = fullscreen, class:steam_app_.*
windowrule = noanim, class:steam_app_.*
windowrule = noblur, class:steam_app_.*
windowrule = noborder, class:steam_app_.*
windowrule = content:game, class:steam_app_.*
windowrule = idleinhibit:fullscreen, class:steam_app_.*
windowrule = keepaspectratio, class:steam_app_.*