[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding="5"

Font="ESPACION"
FontSize="12"

KeyboardSize="0.4"
RoundCorners="20"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d"

HeaderText=""

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/dynamic.jpg"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.0"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

HeaderTextColor="{{colors.primary.dark.hex}}"
DateTextColor="{{colors.primary.dark.hex}}"
TimeTextColor="{{colors.tertiary.dark.hex}}"

FormBackgroundColor="{{colors.surface_container.dark.hex}}"
BackgroundColor="{{colors.primary.dark.hex}}"
DimBackgroundColor="{{colors.secondary_container.dark.hex}}"

LoginFieldBackgroundColor="{{colors.surface_container_high.dark.hex}}"
PasswordFieldBackgroundColor="{{colors.surface_container_high.dark.hex}}"
LoginFieldTextColor="{{colors.on_surface.dark.hex}}"
PasswordFieldTextColor="{{colors.on_surface.dark.hex}}"
UserIconColor="{{colors.on_surface.dark.hex}}"
PasswordIconColor="{{colors.on_surface.dark.hex}}"

PlaceholderTextColor="{{colors.on_surface_variant.dark.hex}}"
WarningColor="{{colors.error.dark.hex}}"

LoginButtonTextColor="#ffffff"
LoginButtonBackgroundColor="{{colors.primary.dark.hex}}"
SystemButtonsIconsColor="{{colors.tertiary.dark.hex}}"
SessionButtonTextColor="{{colors.tertiary.dark.hex}}"
VirtualKeyboardButtonTextColor="{{colors.tertiary.dark.hex}}"

DropdownTextColor="#ffffff"
DropdownSelectedBackgroundColor="{{colors.primary.dark.hex}}"
DropdownBackgroundColor="{{colors.surface_container.dark.hex}}"

HighlightTextColor="{{colors.background.dark.hex}}"
HighlightBackgroundColor="{{colors.tertiary.dark.hex}}"
HighlightBorderColor="{{colors.primary.dark.hex}}"

HoverUserIconColor="{{colors.primary.dark.hex}}"
HoverPasswordIconColor="{{colors.primary.dark.hex}}"
HoverSystemButtonsIconsColor="{{colors.primary.dark.hex}}"
HoverSessionButtonTextColor="{{colors.primary.dark.hex}}"
HoverVirtualKeyboardButtonTextColor="{{colors.primary.dark.hex}}"

#################### Form ####################

PartialBlur="false"
FullBlur="false"
BlurMax="32"
Blur="1.0"

HaveFormBackground="true"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="left"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

#################### Translation ####################

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
