# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Autostart Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

source = ~/.config/hypr/config/defaults.conf

# Autostart wiki https://wiki.hyprland.org/Configuring/Keywords/#executing

# exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE XDG_RUNTIME_DIR

# Slow app launch fix
exec-once = systemctl --user import-environment
exec-once = hash dbus-update-activation-environment 2>/dev/null
exec-once = dbus-update-activation-environment --systemd --all

# Input Method in daemon (-d) mode
exec-once = fcitx5 -d &

# Authentication Dialogs
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &

# Gnome Keyring
exec-once = /usr/bin/gnome-keyring-daemon --start --components=secrets,ssh

# Waybar, swaync and wallpaper init
exec-once = ~/dotfiles/go-scripts/wallpaper --random --sddm &

# Load clipboard history watcher
exec-once = wl-paste --watch cliphist store &

# Disable Hypridle when fullscreen is active for any tile or any media is playing. Also starts up hypridle.
exec-once = ~/dotfiles/go-scripts/hypridle-inhibit --daemon &

# Spawn and pin the per-monitor "1" workspaces with reversed invisibles
exec-once = $HYPRSCRIPTS/workspace-init.sh 'LG Electronics LG ULTRAGEAR+ 411NTTQ06481' 'LG Electronics LG ULTRAGEAR+ 402NTJJB7972' &

# Swayosd for on-screen display of volume/brightness changes
exec-once = swayosd-server &

# Network manager applet
exec-once = nm-applet &

# Solaar daemon to retrieve peripheral information (battery status)
exec-once = solaar -w hide &

# Apps
exec-once = ~/dotfiles/go-scripts/run-when --days "Mon..Fri" --start 06:00 --end 17:00 -- gtk-launch microsoft-teams &
exec-once = steam -forcedesktopscaling 1.5 -silent &
exec-once = discord --start-minimized &