# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


# General
$filemanager = thunar
$applauncher = wofi
$terminal = kitty
$HYPRSCRIPTS = ~/.config/hypr/scripts

# Screenshots
$shot-region = grimblast copy area && wl-paste --type image/png > ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png
$shot-window = grimblast copy active && wl-paste --type image/png > ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png
$shot-screen = grimblast copy output && wl-paste --type image/png > ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png