# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

env = HYPRCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Breeze_Light
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Breeze_Light
env = QT_CURSOR_SIZE,24

env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_SCALE_FACTOR_ROUNDING_POLICY,PassThrough   # avoids weird rounding on HiDPI

# NVIDIA https://wiki.hyprland.org/Nvidia/
env = GBM_BACKEND,nvidia-drm
env = LIBVA_DRIVER_NAME,nvidia
env = SDL_VIDEODRIVER,wayland
# env = WLR_DRM_NO_ATOMIC,1
# env = __GL_VRR_ALLOWED,1
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __NV_PRIME_RENDER_OFFLOAD,1
env = __VK_LAYER_NV_optimus,NVIDIA_only

# FOR VM and POSSIBLY NVIDIA
env = WLR_NO_HARDWARE_CURSORS,1 # On hyprland >v0.41, now configured on variable cursor section
env = WLR_RENDERER_ALLOW_SOFTWARE,1

# nvidia firefox (for hardware acceleration on FF)?
# FOLLOW THIS POST
# https://github.com/elFarto/nvidia-vaapi-driver#configuration
env = MOZ_DISABLE_RDD_SANDBOX,1
env = EGL_PLATFORM,wayland
env = __EGL_VENDOR_LIBRARY_FILENAMES,/usr/share/glvnd/egl_vendor.d/10_nvidia.json

cursor {
    no_hardware_cursors = true
}