# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Monitor Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Monitor wiki https://wiki.hyprland.org/Configuring/Monitors/

monitor=desc:LG Electronics LG ULTRAGEAR+ 411NTTQ06481,preferred,0x0,1.25
# monitor=desc:LG Electronics LG ULTRAGEAR 310NTCZ6H379,3440x1440@160,-1440x-1560,1.0,transform,1
monitor=desc:LG Electronics LG ULTRAGEAR 310NTCZ6H379,3440x1440@160,-1440x-1360,1.0,transform,1


# If you need to scale things like steam etc, please uncomment these lines.
xwayland {
 force_zero_scaling = true       # Unscale XWayland
}

# Adjust GDK_SCALE accordingly to your liking.
# env = GDK_SCALE, 1.25                   # GDK Scaling Factor
