# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Monitor Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Monitor wiki https://wiki.hyprland.org/Configuring/Monitors/

# Since I use 4k displays with a scale of 1.25, they effectively get a 3072x1728 resolution
# 3840 / 1.25 = 3072
# 2160 / 1.25 = 1728

# monitor=desc:LG Electronics LG ULTRAGEAR+ 411NTTQ06481,3840x2160@240,0x0,1.25
monitor=desc:LG Electronics LG ULTRAGEAR+ 411NTTQ06481,preferred,0x0,1
# monitor=desc:LG Electronics LG ULTRAGEAR+ 402NTJJB7972,preferred,-1728x-850,1,transform,1
monitor=desc:LG Electronics LG ULTRAGEAR+ 402NTJJB7972,preferred,-2160x-1040,1,transform,1


# If you need to scale things like steam etc, please uncomment these lines.
xwayland {
 force_zero_scaling = true       # Unscale XWayland
}

# Adjust GDK_SCALE accordingly to your liking.
# env = GDK_SCALE, 1.25                   # GDK Scaling Factor
